package com.java.mvc.view;

import java.awt.Dimension;
import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

public class Screen extends JFrame {

	/*
	 * Creating a new Screen form
	 */
	public Screen() {
		initComponents();
	}
	
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		pnlPanel = new JPanel();
		jLabel1 = new JLabel();
		txtCode = new JTextField();
		jLabel2 = new JLabel();
		txtName = new JTextField();
		jLabel3 = new JLabel();
		txtPrice = new JTextField();
		btnInsert = new JButton();
		btnSelect = new JButton();
		btnAlter = new JButton();
		btnClear = new JButton();
		jScrollPane1 = new JScrollPane();
		tblExample = new JTable();
		btnDelete = new JButton();
		btnNewSearch = new JButton();
		
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		setTitle("Table example");
		setMaximumSize(new Dimension(800, 600));
		setMinimumSize(new Dimension(800, 600));
		setResizable(false);
		
		pnlPanel.setMaximumSize(new Dimension(800, 600));
		pnlPanel.setMinimumSize(new Dimension(800, 600));
		pnlPanel.setPreferredSize(new Dimension(800, 600));
		
		jLabel1.setFont(new Font("Arial", 0, 14));
		jLabel1.setText("Code");
		
		txtCode.setFont(new Font("Arial", 0, 14));
		
		jLabel2.setFont(new Font("Arial", 0, 14));
		jLabel2.setText("Product name");
		
		txtName.setFont(new Font("Arial", 0, 14));
		
		jLabel3.setFont(new Font("Arial", 0, 14));
		jLabel3.setText("Price");
		
		txtPrice.setFont(new Font("Arial", 0, 14));
		
		btnInsert.setFont(new Font("Arial", 0, 14));
		btnInsert.setText("Insert");
		
		btnSelect.setFont(new Font("Arial", 0, 14));
		btnSelect.setText("Select");
		
		btnAlter.setFont(new Font("Arial", 0, 14));
		btnAlter.setText("Alter");
		
		btnClear.setFont(new Font("Arial", 0, 14));
		btnClear.setText("Clear entry");
		
		tblExample.setFont(new Font("Arial", 0, 14));
		tblExample.setModel(new DefaultTableModel(
			new Object [][] {
				
			},
			new String [] {
				"Code", "Product", "Price"
			}
			){
			Class[] types = new Class [] {
				Integer.class, String.class, Double.class
			};
	
			public Class getColumnsClass(int columnIndex) {
				return types [columnIndex];
			}
		});
		tblExample.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblExample);

        btnDelete.setFont(new Font("Arial", 0, 14)); // NOI18N
        btnDelete.setText("Delete");

        btnNewSearch.setFont(new Font("Arial", 0, 14)); // NOI18N
        btnNewSearch.setText("New search");

        GroupLayout pnlPanelLayout = new GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCode, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, GroupLayout.PREFERRED_SIZE, 439, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 673, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(35, 35, 35)
                        .addComponent(btnSelect)
                        .addGap(32, 32, 32)
                        .addComponent(btnAlter)
                        .addGap(27, 27, 27)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewSearch)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(75, 75, 75))))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnSelect)
                    .addComponent(btnAlter)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnNewSearch))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 304, GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	// Getters
	public JButton getBtnAlter() {
		return btnAlter;
	}

	public JButton getBtnDelete() {
		return btnDelete;
	}

	public JButton getBtnInsert() {
		return btnInsert;
	}

	public JButton getBtnClear() {
		return btnClear;
	}

	public JButton getBtnNewSearch() {
		return btnNewSearch;
	}

	public JButton getBtnSelect() {
		return btnSelect;
	}

	public JLabel getJLabel1() {
		return jLabel1;
	}

	public JLabel getJLabel2() {
		return jLabel2;
	}

	public JLabel getJLabel3() {
		return jLabel3;
	}

	public JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public JPanel getPnlPanel() {
		return pnlPanel;
	}

	public JTable getTblExample() {
		return tblExample;
	}

	public JTextField getTxtCode() {
		return txtCode;
	}

	public JTextField getTxtName() {
		return txtName;
	}

	public JTextField getTxtPrice() {
		return txtPrice;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton btnAlter;
	private JButton btnDelete;
	private JButton btnInsert;
	private JButton btnClear;
	private JButton btnNewSearch;
	private JButton btnSelect;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JScrollPane jScrollPane1;
	private JPanel pnlPanel;
	private JTable tblExample;
	private JTextField txtCode;
	private JTextField txtName;
	private JTextField txtPrice;
	// End of variables declaration//GEN-END:variables
}